# Brief Summary of Processed Files
The purpose of this file is to summarize some of the processed files (i.e., dataframes) by reading their first few rows, to give a sense how the processed data look like. For data privacy concerns, not all the dataframes are shown.

In [4]:
### Filtration volume

import pandas as pd
df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\filtration_volume.xlsx')
df.head()

,Unnamed: 0,FV C,FV F,FV All,FV C Error,FV F Error,FV All Error
0,0,14000.779048,1799.925014,15800.704061,1153.586787,214.946646,1173.441322
1,1,28343.430358,498.498335,28841.928693,2200.377741,55.623742,2201.080690
2,2,53697.116449,332.032502,54029.148951,4274.485877,38.177065,4274.656361
3,3,18648.085343,331.916076,18980.001419,1509.850133,38.897750,1510.351105
4,4,0.000000,209947.359695,209947.359695,0.000000,23206.921305,23206.921305

In [6]:
### PM value efficiecies by Mini-WRAS

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\mini_wras_eff_pm.xlsx')
df.head()

,PM,Initial,Initial Error,Final,Final Error,Overall,Overall Error
0,PM10,79.587398,4.779092,89.414050,4.205071,84.500724,3.182858
1,PM2.5,56.830577,10.214418,39.961627,15.317004,48.396102,9.205229
2,PM1,36.252515,15.245947,16.914382,20.323560,26.583449,12.703208
3,PM2.5_10,92.640004,2.240770,99.391374,0.512107,96.015689,1.149272
4,PM1_2.5,79.011929,4.954262,87.580349,4.709495,83.296139,3.417750

In [8]:
### Size-resolved filter fficiecies by Mini-WRAS

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\mini_wras_eff.xlsx')
df.head(10)

,Size,Initial,Initial Error,Final,Final Error,Overall,Overall Error
0,0.100,36.874389,16.444508,28.158988,17.567812,32.516689,12.031728
1,0.139,23.634721,18.786950,14.587809,20.129205,19.111265,13.767120
2,0.193,19.166222,18.382480,-28.336871,31.963697,-4.585324,18.436333
3,0.253,36.992374,15.792964,2.692723,24.165463,19.842549,14.434224
4,0.298,39.619148,14.737156,3.315082,23.795801,21.467115,13.994855
5,0.352,41.834136,14.328971,5.329905,23.193643,23.582020,13.631439
6,0.414,41.555551,14.178170,11.459376,21.528904,26.507463,12.889087
7,0.488,49.700198,11.988569,5.157498,22.928830,27.428848,12.936934
8,0.576,50.473747,11.775108,36.890663,16.021036,43.682205,9.941413
9,0.679,54.752740,10.476946,43.545993,15.409443,49.149366,9.316885

In [17]:
### PSD measured by QFF (detailed)

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\psd_qff_evaluation.xlsx')
df.iloc[15:,:].head(10)

,Size,qff_eval_f00_D_190727_am_count,qff_eval_f00_D_190727_am_r2_count,qff_eval_f00_S_190727_am_count,qff_eval_f00_D_190727_am_median,qff_eval_f00_D_190727_am_r2_median,qff_eval_f00_S_190727_am_median,qff_eval_f00_D_190727_am_mean,qff_eval_f00_D_190727_am_r2_mean,qff_eval_f00_S_190727_am_mean,qff_eval_f00_D_190727_am_std,qff_eval_f00_D_190727_am_r2_std,qff_eval_f00_S_190727_am_std,qff_eval_f00_D_190727_am_min,qff_eval_f00_D_190727_am_r2_min,qff_eval_f00_S_190727_am_min,qff_eval_f00_D_190727_am_max,qff_eval_f00_D_190727_am_r2_max,qff_eval_f00_S_190727_am_max
15,0.562,5,5,5,0.00,0.00,0.00,0.000,0.000,0.000,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000
16,0.631,5,5,5,0.00,0.00,0.00,0.000,0.000,0.000,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000
17,0.708,5,5,5,0.00,0.00,0.00,0.000,0.000,0.000,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000
18,0.794,5,5,5,0.00,0.00,0.00,0.000,0.000,0.004,0.000000,0.000000,0.005477,0.000,0.000,0.004,0.000,0.000,0.006
19,0.891,5,5,5,0.01,0.01,0.01,0.010,0.010,0.030,0.000000,0.000000,0.027386,0.000,0.000,0.020,0.000,0.000,0.030
20,1.000,5,5,5,0.06,0.06,0.09,0.060,0.060,0.086,0.000000,0.000000,0.011402,0.000,0.000,0.016,0.000,0.000,0.014
21,1.120,5,5,5,0.09,0.09,0.12,0.092,0.090,0.124,0.004472,0.000000,0.011402,0.002,0.000,0.014,0.008,0.000,0.016
22,1.260,5,5,5,0.12,0.12,0.15,0.118,0.120,0.148,0.004472,0.000000,0.014832,0.008,0.000,0.018,0.002,0.000,0.022
23,1.410,5,5,5,0.15,0.15,0.18,0.146,0.150,0.180,0.005477,0.000000,0.015811,0.006,0.000,0.020,0.004,0.000,0.020
24,1.580,5,5,5,0.19,0.20,0.22,0.188,0.196,0.222,0.004472,0.005477,0.019235,0.008,0.006,0.022,0.002,0.004,0.028

In [19]:
### PSD measured by QFF (summary)

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\psd_qff.xlsx')
df.iloc[15:,:].head(15)

     Size   qff psd  qff psd error
15  0.562  0.000000       0.000000
16  0.631  0.000000       0.000000
17  0.708  0.000000       0.000000
18  0.794  0.000000       0.000000
19  0.891  0.017071       0.002535
20  1.000  0.095827       0.014383
21  1.120  0.171745       0.037067
22  1.260  0.209347       0.041278
23  1.410  0.205427       0.023900
24  1.580  0.252694       0.025095
25  1.780  0.290044       0.026547
26  2.000  0.338697       0.030309
27  2.240  0.372349       0.028525
28  2.510  0.441640       0.030513
29  2.820  0.520186       0.032495

In [21]:
### Sioutas Cascade Impactor PSD

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\psd_sci_unstack.xlsx')
df.head()

  FP  PM Mass     Error  Mass Perc  Mass Perc Error   Size  Max Size
0  A   0.9745  0.000044  10.031250         0.452963  2.510    10.000
1  B   0.3497  0.000044   3.599721         0.174653  1.000     2.510
2  C   0.1448  0.000044   1.490534         0.095459  0.501     1.000
3  D   0.8059  0.000044   8.295725         0.376567  0.251     0.501
4  E   2.1195  0.000044  21.817582         0.976264  0.100     0.251

In [25]:
### Trace metals airborne and QFF concentrations

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\tm_qff.xlsx')
df.head(15)

   Element  Concentration     Error measure
0       Pb       1.968933  0.124715      ab
1       As       0.744507  0.053996      ab
2       Cd       0.075061  0.030781      ab
3       Cu       3.302486  0.163516      ab
4       Zn      20.093300  1.067536      ab
5       Ni       0.539713  0.196050      ab
6        K      50.827636  3.125699      ab
7       Ti       8.831450  2.211995      ab
8        V       0.173944  0.051833      ab
9       Fe      71.420661  3.350204      ab
10      Sr       0.855867  0.075085      ab
11      Sb       0.405243  0.040904      ab
12      Pb       2.432013  0.926086     qff
13      As       0.157391  0.060008     qff
14      Cd       0.066420  0.025307     qff

In [31]:
### QFF PM concentrations

df = pd.read_excel(r'C:\PhD Research\QFF Evaluation\Processed\qff_pm.xlsx')
df.head()

         PM  Concentration     Error Measure
0      PM10       2.409880  0.414187     qff
1     PM2.5       0.620003  0.159299     qff
2       PM1       0.009865  0.004995     qff
3  PM2.5_10       1.808360  0.303930     qff
4   PM1_2.5       0.357081  0.063426     qff

End of Code